import {
  CognitoIdentityProviderClient,
  AdminCreateUserCommand,
  AttributeType
} from '@aws-sdk/client-cognito-identity-provider';
import fs from 'fs';

/**
 * BeboCard Cognito User Pool Restore Script (P0-6 DR)
 * 
 * Usage:
 *   node scripts/cognito-restore.js <new-pool-id> <path-to-export.json> <region>
 * 
 * DESCRIPTION:
 * Reads a JSON export generated by the 'cognito-export' Lambda and recreates
 * all users in a newly provisioned Cognito User Pool.
 * 
 * CRITICAL LIMITATIONS:
 * 1. Passwords ARE NOT migrated (Cognito does not export hashes). Users will 
 *    be created with FORCE_CHANGE_PASSWORD and must reset on first login.
 * 2. User status (CONFIRMED, UNCONFIRMED, etc.) is reset — all users enter
 *    the pool as 'FORCE_CHANGE_PASSWORD'.
 */

const [poolId, exportPath, region] = process.argv.slice(2);

if (!poolId || !exportPath || !region) {
  console.error('Usage: node scripts/cognito-restore.js <new-pool-id> <path-to-export.json> <region>');
  process.exit(1);
}

const client = new CognitoIdentityProviderClient({ region });

async function restore() {
  console.log(`[DR] Starting restoration of users into pool ${poolId} from ${exportPath}...`);

  let data;
  try {
    const raw = fs.readFileSync(exportPath, 'utf8');
    data = JSON.parse(raw);
  } catch (err) {
    console.error(`[DR] Failed to read or parse export file: ${err.message}`);
    process.exit(1);
  }

  const users = data.users || [];
  console.log(`[DR] Identified ${users.length} users to restore.`);

  let success = 0;
  let failure = 0;

  for (const user of users) {
    try {
      // Map attributes back to Cognito format
      const attributes: AttributeType[] = [];
      for (const [name, value] of Object.entries(user.Attributes || {})) {
        // Skip sub (it's automatically generated in the new pool)
        if (name === 'sub') continue;
        
        attributes.push({
          Name: name,
          Value: value as string
        });
      }

      await client.send(new AdminCreateUserCommand({
        UserPoolId: poolId,
        Username: user.Username,
        UserAttributes: attributes,
        MessageAction: 'SUPPRESS', // Don't spam users during a disaster recovery
        TemporaryPassword: 'Temp' + Math.random().toString(36).slice(-8) + '!', // Random temp password
      }));

      success++;
      if (success % 10 === 0) console.log(`[DR] Restored ${success}/${users.length} users...`);
    } catch (err) {
      console.error(`[DR] Failed to restore user ${user.Username}: ${err.message}`);
      failure++;
    }
  }

  console.log(`[DR] Restore complete.`);
  console.log(`[DR] Success: ${success}`);
  console.log(`[DR] Failure: ${failure}`);
  console.log(`[DR] NOTE: All users must reset their passwords via 'Forgot Password' in the BeboCard app.`);
}

restore();
